import type { Funcao, Militar } from './types';

export const FUNCOES: Funcao[] = [
  "COMANDANTE DO 1º SOCORRO",
  "COMANDANTE DO 2º SOCORRO",
  "BUSCA E SALVAMENTO"
];

export const MILITARES_INICIAIS: Militar[] = [
  { rg: "17211", grad: "1° TEN", quadro: "QOA", nome: "ALEXANDRE GOMES", unidade: "1ª ODONTO" },
  { rg: "27573", grad: "1° TEN", quadro: "QOE/COM", nome: "MARCILIANO", unidade: "BM/1" },
  { rg: "26843", grad: "1° TEN", quadro: "QOA", nome: "ÚRSULA", unidade: "ARINST" },
  { rg: "26767", grad: "1° TEN", quadro: "QOA", nome: "NELMA", unidade: "CHC" },
  { rg: "14879", grad: "1° TEN", quadro: "QOA", nome: "CARLOS RODRIGUES", unidade: "SCP" },
  { rg: "30596", grad: "CAP", quadro: "QOA", nome: "ANÉSIA", unidade: "CONTROLADORIA" },
  { rg: "15923", grad: "CAP", quadro: "QOA", nome: "WANDERLAN GOMES", unidade: "DGEAO" },
  { rg: "26863", grad: "1° TEN", quadro: "QOA", nome: "SELMA SILVEIRA", unidade: "ARINST" },
  { rg: "15356", grad: "CAP", quadro: "QOA", nome: "SÉRGIO LOURENÇO", unidade: "CRVD" },
  { rg: "31298", grad: "1° TEN", quadro: "QOE/MUS", nome: "ABREU", unidade: "GBMus" },
  { rg: "18554", grad: "1° TEN", quadro: "QOA", nome: "QUEIMA", unidade: "CHC" },
  { rg: "27476", grad: "1° TEN", quadro: "QOA", nome: "MESQUITA", unidade: "DGAF" },
  { rg: "12914", grad: "CAP", quadro: "QOA", nome: "OMAR DINIZ", unidade: "DGVP" },
  { rg: "10311", grad: "CAP", quadro: "QOA", nome: "ALEXANDRE ALMEIDA", unidade: "CH. GAB. SEDEC" },
  { rg: "26834", grad: "1° TEN", quadro: "QOA", nome: "FABÍOLA", unidade: "CONTROLADORIA" },
  { rg: "12267", grad: "CAP", quadro: "QOA", nome: "SOUZA COELHO", unidade: "SUAD" },
  { rg: "11537", grad: "CAP", quadro: "QOA", nome: "CLÁUDIO JOSÉ", unidade: "CRD" },
  { rg: "12313", grad: "CAP", quadro: "QOA", nome: "MARCELO CORREA", unidade: "DGVP" },
  { rg: "26745", grad: "1° TEN", quadro: "QOA", nome: "JACQUELINE MENDES", unidade: "DGP" },
  { rg: "31365", grad: "1° TEN", quadro: "QOA", nome: "J.FÉLIX", unidade: "CHC" },
  { rg: "22037", grad: "1° TEN", quadro: "QOA", nome: "ORLANDO", unidade: "DGVP" },
  { rg: "12961", grad: "CAP", quadro: "QOA", nome: "J.SANTOS", unidade: "GOCG" },
  { rg: "15655", grad: "CAP", quadro: "QOA", nome: "MARQUES SOUZA", unidade: "CONTROLADORIA" },
  { rg: "11380", grad: "CAP", quadro: "QOA", nome: "PATROCÍNIO", unidade: "DGVP" },
  { rg: "20123", grad: "CAP", quadro: "QOA", nome: "ALEXANDRE AMORIM", unidade: "DGP" },
  { rg: "53382", grad: "CAP", quadro: "QOC", nome: "GUILHERME RODRIGUES", unidade: "DGPAT" },
  { rg: "46083", grad: "CAP", quadro: "QOC", nome: "RIGO", unidade: "DGAF" },
  { rg: "47143", grad: "CAP", quadro: "QOC", nome: "RENATO MELO", unidade: "DGAF" },
  { rg: "45327", grad: "CAP", quadro: "QOC", nome: "THIAGO SOARES", unidade: "ASSEJUR" },
  { rg: "48087", grad: "CAP", quadro: "QOC", nome: "BRASIL", unidade: "DGAF" },
  { rg: "48082", grad: "CAP", quadro: "QOC", nome: "THIAGO COSTA", unidade: "SCP" },
  { rg: "49941", grad: "CAP", quadro: "QOC", nome: "CARRIJO", unidade: "ASTI" },
  { rg: "53405", grad: "CAP", quadro: "QOC", nome: "HAWAD", unidade: "DGST" },
  { rg: "49126", grad: "CAP", quadro: "QOC", nome: "VITOR MAGALHÃES", unidade: "FUNESBOM" },
  { rg: "48089", grad: "CAP", quadro: "QOC", nome: "VICTOR RAPOSO", unidade: "DGF" },
  { rg: "23651", grad: "CAP", quadro: "QOC", nome: "WESLEI", unidade: "ARINST" },
  { rg: "48097", grad: "CAP", quadro: "QOC", nome: "PEDRO FILIPPO", unidade: "DGAF" },
  { rg: "36306", grad: "CAP", quadro: "QOC", nome: "LEÃO", unidade: "DGST" },
  { rg: "46073", grad: "CAP", quadro: "QOC", nome: "IMPRONTA", unidade: "ASTI" },
  { rg: "46112", grad: "CAP", quadro: "QOC", nome: "FREITAS", unidade: "BM/3" },
  { rg: "45304", grad: "CAP", quadro: "QOC", nome: "JEANNE", unidade: "DGP" },
  { rg: "49113", grad: "CAP", quadro: "QOC", nome: "TAMIRIS", unidade: "ASSEJUR" },
  { rg: "48075", grad: "CAP", quadro: "QOC", nome: "FELIPE PEREIRA", unidade: "DGST" },
  { rg: "49141", grad: "CAP", quadro: "QOC", nome: "BUSSAD", unidade: "CORREGEDORIA GERAL" },
  { rg: "53343", grad: "CAP", quadro: "QOC", nome: "JOANA CAMILO", unidade: "DGF" },
  { rg: "49937", grad: "CAP", quadro: "QOC", nome: "VANZAN", unidade: "ASTI" },
  { rg: "49205", grad: "CAP", quadro: "QOC", nome: "DIOGO DIAS", unidade: "DGF" },
  { rg: "46101", grad: "CAP", quadro: "QOC", nome: "GOIS", unidade: "CHC" },
  { rg: "48113", grad: "CAP", quadro: "QOC", nome: "THAIS", unidade: "AJG" },
  { rg: "49925", grad: "CAP", quadro: "QOC", nome: "BRUNO GONÇALVES", unidade: "DGST" },
  { rg: "48108", grad: "CAP", quadro: "QOC", nome: "LORAN", unidade: "DGAF" },
  { rg: "49128", grad: "CAP", quadro: "QOC", nome: "RICARDO FARIA", unidade: "DGST" },
  { rg: "53312", grad: "CAP", quadro: "QOC", nome: "THALLES FILIPE", unidade: "FUNESBOM" },
  { rg: "49170", grad: "CAP", quadro: "QOC", nome: "JUDSON", unidade: "DGAF" },
  { rg: "49934", grad: "CAP", quadro: "QOC", nome: "ANDRÉ CARDOSO", unidade: "GOCG" },
  { rg: "48081", grad: "CAP", quadro: "QOC", nome: "RENAN MARQUES", unidade: "DGVP" },
  { rg: "44010", grad: "CAP", quadro: "QOC", nome: "DIEGO CAETANO", unidade: "FUNESBOM" },
  { rg: "47115", grad: "CAP", quadro: "QOC", nome: "FABRÍCIO CHAVES", unidade: "DGP" },
  { rg: "46081", grad: "CAP", quadro: "QOC", nome: "HENRI COSTA", unidade: "GOCG" },
  { rg: "48077", grad: "CAP", quadro: "QOC", nome: "RAISSA", unidade: "DGPAT" },
  { rg: "48070", grad: "CAP", quadro: "QOC", nome: "CASSIO LIMA", unidade: "DGAF" },
  { rg: "53362", grad: "CAP", quadro: "QOC", nome: "BRANCO", unidade: "DGAF" },
  { rg: "49933", grad: "CAP", quadro: "QOC", nome: "IGOR MOTTA", unidade: "NUPROEISBM" },
  { rg: "53346", grad: "CAP", quadro: "QOC", nome: "MOREIRA", unidade: "DGF" },
  { rg: "33846", grad: "CAP", quadro: "QOC", nome: "FILGUEIRA", unidade: "DGF" },
  { rg: "49120", grad: "CAP", quadro: "QOC", nome: "ESTEVÃO", unidade: "DGVP" },
  { rg: "53717", grad: "2° TEN", quadro: "QOC", nome: "THIAGO SANTOS", unidade: "GOCG" },
  { rg: "53332", grad: "CAP", quadro: "QOC", nome: "LARISSA QUEIROZ", unidade: "DGST" },
  { rg: "53515", grad: "1° TEN", quadro: "QOC", nome: "OSMAR", unidade: "GOCG" },
  { rg: "49197", grad: "CAP", quadro: "QOC", nome: "JULIO", unidade: "DGP" },
  { rg: "48112", grad: "CAP", quadro: "QOC", nome: "TÁSSIA", unidade: "ACS" },
  { rg: "43935", grad: "CAP", quadro: "QOC", nome: "RUBENS PORTES", unidade: "DGST" },
  { rg: "49158", grad: "CAP", quadro: "QOC", nome: "ALLAN AMORIM", unidade: "SUBSEDEC" },
  { rg: "49149", grad: "CAP", quadro: "QOC", nome: "PATRICK MACHADO", unidade: "DGVP" },
  { rg: "49913", grad: "CAP", quadro: "QOC", nome: "REIS MONTEIRO", unidade: "ASSEJUR" },
  { rg: "48093", grad: "CAP", quadro: "QOC", nome: "NAVARRO", unidade: "ASSEMG" },
  { rg: "53444", grad: "1° TEN", quadro: "QOC", nome: "THIAGO SILVA", unidade: "GOCG" },
  { rg: "53518", grad: "1° TEN", quadro: "QOC", nome: "SILAS CUNHA", unidade: "ACS" },
  { rg: "48099", grad: "CAP", quadro: "QOC", nome: "REZENDE", unidade: "DGVP" },
  { rg: "49153", grad: "CAP", quadro: "QOC", nome: "JOÃO RODRIGUES", unidade: "ASSEJUR" },
  { rg: "48088", grad: "CAP", quadro: "QOC", nome: "MARCOS JUNIOR", unidade: "ASSEMG" },
  { rg: "46095", grad: "CAP", quadro: "QOC", nome: "LUIZ DEMARCO", unidade: "ASTI" },
  { rg: "49127", grad: "CAP", quadro: "QOC", nome: "JÉSSICA DIAS", unidade: "ASSEJUR" },
  { rg: "53353", grad: "CAP", quadro: "QOC", nome: "BRENO ALVES", unidade: "DGVP" },
  { rg: "53485", grad: "1° TEN", quadro: "QOC", nome: "FILIPE ARAUJO", unidade: "GOCG" },
  { rg: "53483", grad: "1° TEN", quadro: "QOC", nome: "JULIANA PEREIRA", unidade: "SUAD" },
  { rg: "49107", grad: "CAP", quadro: "QOC", nome: "MATHEUS LEÃO", unidade: "FUNESBOM" },
  { rg: "53726", grad: "2° TEN", quadro: "QOC", nome: "FORTES", unidade: "GOCG" },
  { rg: "53321", grad: "CAP", quadro: "QOC", nome: "JÉSSICA VARGAS", unidade: "DGAL" },
  { rg: "49143", grad: "CAP", quadro: "QOC", nome: "MONNERAT", unidade: "DGAL" },
  { rg: "49114", grad: "CAP", quadro: "QOC", nome: "JULIENE", unidade: "ASSEJUR" },
  { rg: "47110", grad: "CAP", quadro: "QOC", nome: "FELIPE PORTELA", unidade: "ASTI" },
  { rg: "49109", grad: "CAP", quadro: "QOC", nome: "RAMON", unidade: "DGAF" }
].map(m => ({ ...m, grad: m.grad.replace(/\s+/g, ' ') }));